INSTALL_WIZARD=progress
UAC_WIZARD=off
LICENSE_SELECTION_WIZARD=off
LICENSE_REGISTER_WIZARD=off
LICENSE_INSTALL_WIZARD=off
BLS_CFG_STARTUP_WIZARD=off
BLS_START_STOP_WIZARD=off
BLS_DESIGNATION_WIZARD=progress
BBJ_CFG_STARTUP_WIZARD=off
BBJ_START_STOP_WIZARD=progress
EM_WIZARD=off
FINISH_WIZARD=off
LANGUAGE=en
SPLASH_IMAGE=
INSTALL_LICENSE_AGREE=true
INSTALL_TARGET_DIRECTORY_NON_WIN=/opt/bbx
INSTALL_JAVA_DIRECTORY_NON_WIN=/opt/java/default
INSTALL_CUSTOM_FEATURES=BBj,Barista,JDBC,Demos
BLS_DESIGNATION_CUSTOM=true
BLS_DESIGNATION_SERVERNAME=LICENSE_SERVER_PLACEHOLDER
BLS_DESIGNATION_CERTIFICATE_FILE=/tmp/certificate.bls
BBJ_CFG_STARTUP_TYPE_NON_WIN=manual
BBJ_CFG_STARTUP_USERACCOUNT_NON_WIN=root
BBJ_CFG_STARTUP_PASSWORD_NON_WIN=ENCRYPTED:oDzMA2Q2FFo=
BBJ_START_STOP_STARTUP=start
BBJ_START_STOP_SERVERNAME=localhost
BBJ_START_STOP_ADMINPORT=2002
BBJ_START_STOP_USERPASSWORD=ENCRYPTED:oDzMA2Q2FFo=
BBJ_START_STOP_WAITFORCLIENTS=false
